name: creditlake
version: '1.0.0'
config-version: 2
profile: creditlake
model-paths: [models]
test-paths: [tests]
macro-paths: [macros]
clean-targets: [target, dbt_packages]
models:
  creditlake:
    +schema: analytics
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
    marts:
      +materialized: table
